# Generated by Django 5.2.4 on 2025-07-08 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_estudiante_enfermedad_actual_and_more'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_medical', to='estudiantes.estudiante'),
        ),
    ]
