# Generated by Django 5.2.4 on 2025-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('procedencia', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('padre', models.CharField(blank=True, max_length=100)),
                ('madre', models.CharField(blank=True, max_length=100)),
                ('apoderado', models.CharField(blank=True, max_length=100)),
                ('vive_con', models.CharField(max_length=100)),
                ('total_personas_hogar', models.IntegerField()),
                ('salud', models.CharField(max_length=50)),
                ('enfermedad_actual', models.BooleanField(default=False)),
                ('enfermedad_desc', models.TextField(blank=True)),
                ('atencion_psicologica', models.BooleanField(default=False)),
                ('psicologico_desc', models.TextField(blank=True)),
            ],
        ),
    ]
