# Generated by Django 5.2.4 on 2025-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedad_actual',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='enfermedad',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('asma', 'Asma'), ('diabetes', 'Diabetes'), ('alergia', 'Alergia'), ('epilepsia', 'Epilepsia'), ('cardiopatia', 'Cardiopatía'), ('otra', 'Otra')], default='ninguna', max_length=20),
        ),
    ]
